# Generated by Django 2.2.2 on 2019-06-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_cotent',
            new_name='post_content',
        ),
    ]
